name: Build

on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prepare-versions:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - id: set-matrix
        name: Prepare
        run: echo "matrix=$(node -p "JSON.stringify(require('./package.json').peerDependencies['cypress'].split(' || '))")" >> $GITHUB_OUTPUT
      - run: npm -v

  test:
    needs: prepare-versions
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cypress-version: ${{fromJson(needs.prepare-versions.outputs.matrix)}}
    steps:
      - uses: actions/setup-node@v7
        with:
          node-version: 24
      - name: Checkout
        uses: actions/checkout@v7
      - name: Cache NPM modules
        uses: actions/cache@v6
        with:
          path: ~/.npm
          key: npm-linux@${{ matrix.cypress-version }}
      - name: Cache Cypress binaries
        uses: actions/cache@v6
        with:
          path: ~/.cache/Cypress
          key: cypress-linux@${{ matrix.cypress-version }}
      - name: Dependencies
        env:
          CYPRESS_INSTALL_BINARY: "0"
        run: |
          npm install --engine-strict && \
          npm install --no-save cypress@"${{ matrix.cypress-version }}" && \
          env -u CYPRESS_INSTALL_BINARY npx cypress install
      # Ensures that the 1st test doesn't take abnormally long time and risk timing out.
      - name: Cypress verify
        run: npx cypress verify
      # Ensures no core is dumped during features/browser_crash.feature, during which it would time out.
      - name: Disable coredump
        run: printf "[Coredump]\nStorage=none\nProcessSizeMax=0\n" | sudo tee /etc/systemd/coredump.conf
      - name: Build
        run: npm run build
      - name: Versions
        run: |
          npx cypress --version
          node --version
          npm --version
      - name: Test
        run: npm run test

  windows:
    runs-on: windows-latest
    env:
      NPM_CONFIG_CACHE: ${{ github.workspace }}/.npm
      CYPRESS_CACHE_FOLDER: ${{ github.workspace }}/.cypress
    steps:
      - uses: actions/setup-node@v7
        with:
          node-version: 24
      - name: Checkout
        uses: actions/checkout@v7
      - name: Cache NPM modules
        uses: actions/cache@v6
        with:
          path: .npm
          key: npm-windows
      - name: Cache Cypress binaries
        uses: actions/cache@v6
        with:
          path: .cypress
          key: cypress-windows
      - name: Dependencies
        shell: bash
        run: npm install --engine-strict
      - name: Build
        run: npm run build
      - name: Versions
        run: |
          npx cypress --version
          node --version
          npm --version
      - name: Test (unit)
        run: npm run test:unit
      - name: Test (integration)
        run: npm run test:integration
